/**
 * v0 Reference — Atmospheric Post Card
 * Generated by v0 AI for style extraction. Do NOT use directly.
 * Adapt patterns to existing Feed post cards and AgentGraph's design system.
 *
 * Key patterns:
 * - Bioluminescent border via mask-composite: xor
 * - Glass morphism: rgba(17, 27, 27, 0.8) + backdrop-blur
 * - Gradient avatar ring
 * - Hover: scale + glow intensify
 */

import { useState } from 'react'

interface PostCardProps {
  author: {
    name: string
    avatar: string
    type: 'agent' | 'human'
  }
  content: string
  timestamp: string
  upvotes: number
  replies: number
  isBookmarked?: boolean
  isUpvoted?: boolean
}

export default function PostCard({
  author,
  content,
  timestamp,
  upvotes,
  replies,
  isBookmarked = false,
  isUpvoted = false
}: PostCardProps) {
  const [bookmarked, setBookmarked] = useState(isBookmarked)
  const [upvoted, setUpvoted] = useState(isUpvoted)
  const [currentUpvotes, setCurrentUpvotes] = useState(upvotes)

  const handleUpvote = () => {
    setUpvoted(!upvoted)
    setCurrentUpvotes(prev => upvoted ? prev - 1 : prev + 1)
  }

  return (
    <div className="w-full max-w-2xl mx-auto">
      <div className="group relative p-6 rounded-2xl transition-all duration-500 hover:scale-[1.02] hover:-translate-y-1"
        style={{
          background: 'rgba(17, 27, 27, 0.8)',
          backdropFilter: 'blur(20px)',
          border: '1px solid rgba(30, 51, 51, 0.5)',
        }}
      >
        {/* Animated border glow — key technique */}
        <div
          className="absolute inset-0 rounded-2xl opacity-60 group-hover:opacity-100 transition-opacity duration-500"
          style={{
            background: 'linear-gradient(45deg, #0D9488, #E879F9, #0D9488)',
            backgroundSize: '300% 300%',
            animation: 'borderShift 4s ease-in-out infinite',
            mask: 'linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)',
            WebkitMask: 'linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)',
            maskComposite: 'xor',
            WebkitMaskComposite: 'xor' as never,
            padding: '1px',
          }}
        />

        <div className="relative z-10">
          {/* Header */}
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 rounded-full p-0.5" style={{ background: 'linear-gradient(135deg, #0D9488, #E879F9)' }}>
              <img src={author.avatar} alt={author.name} className="w-full h-full rounded-full object-cover bg-[#111B1B]" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-semibold text-[#CDD6F4]">{author.name}</h3>
                <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                  author.type === 'agent'
                    ? 'bg-[#0D9488]/20 text-[#2DD4BF] border border-[#0D9488]/30'
                    : 'bg-[#E879F9]/20 text-[#E879F9] border border-[#E879F9]/30'
                }`}>
                  {author.type}
                </span>
              </div>
              <span className="text-sm text-[#6C7086]">{timestamp}</span>
            </div>
          </div>

          <p className="text-[#CDD6F4] leading-relaxed mb-6">{content}</p>

          <div className="flex items-center gap-6">
            <button
              onClick={handleUpvote}
              className={`flex items-center gap-2 px-3 py-2 rounded-full transition-all ${
                upvoted ? 'bg-[#0D9488]/20 text-[#2DD4BF]' : 'text-[#6C7086] hover:text-[#CDD6F4]'
              }`}
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
              </svg>
              <span className="text-sm font-medium">{currentUpvotes}</span>
            </button>
            <span className="flex items-center gap-2 text-[#6C7086] text-sm">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
              </svg>
              {replies}
            </span>
            <button
              onClick={() => setBookmarked(!bookmarked)}
              className={`ml-auto p-2 rounded-full transition-all ${
                bookmarked ? 'bg-[#E879F9]/20 text-[#E879F9]' : 'text-[#6C7086] hover:text-[#CDD6F4]'
              }`}
            >
              <svg className="w-4 h-4" fill={bookmarked ? 'currentColor' : 'none'} stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
