/**
 * v0 Reference — Profile Header with Gradient Mesh
 * Generated by v0 AI for style extraction. Do NOT use directly.
 * Adapt patterns to existing Profile page header and AgentGraph's design system.
 *
 * Key patterns:
 * - Gradient mesh: multiple blur-3xl orbs with staggered pulse
 * - Glass morphism: backdrop-blur-xl bg-[#111B1B]/40
 * - Animated gradient avatar border (slow spin)
 * - Gradient text: bg-clip-text text-transparent
 * - Trust score badge with glow shadow
 */

import { useState } from 'react'

interface ProfileHeaderProps {
  avatar: string
  displayName: string
  username: string
  bio: string
  trustScore: number
  stats: { posts: number; followers: number; following: number }
  isFollowing?: boolean
}

export default function ProfileHeader({
  avatar, displayName, username, bio, trustScore, stats, isFollowing = false,
}: ProfileHeaderProps) {
  const [following, setFollowing] = useState(isFollowing)

  const fmt = (n: number) => n >= 1000 ? `${(n / 1000).toFixed(1)}K` : n.toString()

  return (
    <div className="relative w-full max-w-4xl mx-auto">
      {/* Gradient Mesh Background — key technique */}
      <div className="absolute inset-0 overflow-hidden rounded-3xl">
        <div className="absolute inset-0 bg-gradient-to-br from-[#0D9488]/20 via-[#E879F9]/15 to-[#F59E0B]/10" />
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-[#0D9488]/30 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-0 right-1/4 w-80 h-80 bg-[#E879F9]/25 rounded-full blur-3xl animate-pulse [animation-delay:1000ms]" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-64 h-64 bg-[#F59E0B]/20 rounded-full blur-2xl animate-pulse [animation-delay:500ms]" />
      </div>

      {/* Glass Card */}
      <div className="relative backdrop-blur-xl bg-[#111B1B]/40 border border-[#1E3333]/50 rounded-3xl p-8 shadow-2xl">
        <div className="flex flex-col lg:flex-row items-center lg:items-start gap-8">
          {/* Avatar with animated gradient border */}
          <div className="relative shrink-0">
            <div className="relative p-1 rounded-full bg-gradient-to-r from-[#0D9488] via-[#2DD4BF] to-[#E879F9]"
              style={{ animation: 'spin 8s linear infinite' }}
            >
              <div className="w-32 h-32 lg:w-40 lg:h-40 rounded-full bg-[#111B1B] p-1">
                <img src={avatar} alt={displayName} className="w-full h-full rounded-full object-cover" />
              </div>
            </div>
            {/* Trust Score Badge */}
            <div className="absolute -bottom-2 -right-2 bg-gradient-to-r from-[#0D9488] to-[#2DD4BF] rounded-full p-3 shadow-lg">
              <div className="bg-[#111B1B] rounded-full px-3 py-1">
                <div className="flex items-center gap-1">
                  <div className="w-2 h-2 bg-[#2DD4BF] rounded-full animate-pulse shadow-[0_0_8px_#2DD4BF]" />
                  <span className="text-[#CDD6F4] font-bold text-sm">{trustScore}</span>
                </div>
              </div>
            </div>
          </div>

          <div className="flex-1 text-center lg:text-left">
            <h1 className="text-4xl lg:text-5xl font-bold bg-gradient-to-r from-[#0D9488] via-[#2DD4BF] to-[#E879F9] bg-clip-text text-transparent mb-2">
              {displayName}
            </h1>
            <p className="text-[#6C7086] text-lg mb-4">@{username}</p>
            <p className="text-[#CDD6F4] text-lg leading-relaxed mb-6 max-w-2xl">{bio}</p>

            <div className="flex justify-center lg:justify-start gap-8 mb-6">
              {([['Posts', stats.posts], ['Followers', stats.followers], ['Following', stats.following]] as const).map(([label, val]) => (
                <div key={label} className="text-center">
                  <div className="text-2xl font-bold text-[#CDD6F4]">{fmt(val)}</div>
                  <div className="text-[#6C7086] text-sm">{label}</div>
                </div>
              ))}
            </div>

            <button
              onClick={() => setFollowing(!following)}
              className={`px-8 py-3 rounded-full font-semibold text-lg transition-all duration-300 hover:scale-105 active:scale-95 ${
                following
                  ? 'bg-[#1E3333] text-[#CDD6F4] border border-[#1E3333]'
                  : 'bg-gradient-to-r from-[#0D9488] to-[#2DD4BF] text-white shadow-lg shadow-[#0D9488]/25'
              }`}
            >
              {following ? 'Following' : 'Follow'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
