/**
 * v0 Reference — Dashboard Stat Card with Bioluminescent Glow
 * Generated by v0 AI for style extraction. Do NOT use directly.
 * Adapt patterns to existing Dashboard stat cards and AgentGraph's design system.
 *
 * Key patterns:
 * - Outer glow: absolute -inset-0.5 blur-sm animate-pulse
 * - Glass morphism: bg-[#111B1B]/40 backdrop-blur-xl
 * - Inner hover glow: bg-gradient-to-br from-primary/5 to-primary-light/5
 * - Teal shadow intensifying on hover: shadow-[#0D9488]/10
 * - Count-up: requestAnimationFrame + easeOutQuart
 * - Tabular nums for stable width
 */

import { useState, useEffect } from 'react'

interface StatCardProps {
  icon: React.ReactNode
  value: number
  label: string
  duration?: number
}

export default function StatCard({ icon, value, label, duration = 2000 }: StatCardProps) {
  const [displayValue, setDisplayValue] = useState(0)

  useEffect(() => {
    let startTime: number
    let raf: number

    const animate = (timestamp: number) => {
      if (!startTime) startTime = timestamp
      const progress = Math.min((timestamp - startTime) / duration, 1)
      const easeOutQuart = 1 - Math.pow(1 - progress, 4)
      setDisplayValue(Math.floor(easeOutQuart * value))
      if (progress < 1) raf = requestAnimationFrame(animate)
    }

    raf = requestAnimationFrame(animate)
    return () => cancelAnimationFrame(raf)
  }, [value, duration])

  return (
    <div className="group relative">
      {/* Animated glow border — key technique */}
      <div className="absolute -inset-0.5 bg-gradient-to-r from-[#0D9488] via-[#2DD4BF] to-[#0D9488] rounded-xl opacity-20 blur-sm animate-pulse group-hover:opacity-40 transition-opacity duration-500" />

      {/* Glass card */}
      <div className="relative bg-[#111B1B]/40 backdrop-blur-xl border border-[#1E3333] rounded-xl p-6 transition-all duration-500 group-hover:bg-[#111B1B]/60 group-hover:border-[#0D9488]/30 group-hover:shadow-lg group-hover:shadow-[#0D9488]/10">
        {/* Icon */}
        <div className="mb-4">
          <div className="w-12 h-12 rounded-lg bg-gradient-to-br from-[#0D9488] to-[#2DD4BF] p-2.5 shadow-lg shadow-[#0D9488]/20 group-hover:shadow-[#0D9488]/30 transition-shadow duration-300">
            {icon}
          </div>
        </div>

        {/* Stat */}
        <div className="mb-2">
          <span className="text-3xl font-bold text-[#CDD6F4] tabular-nums tracking-tight">
            {displayValue.toLocaleString()}
          </span>
        </div>

        {/* Label */}
        <div className="text-sm text-[#6C7086] font-medium">{label}</div>

        {/* Inner hover glow */}
        <div className="absolute inset-0 rounded-xl bg-gradient-to-br from-[#0D9488]/5 via-transparent to-[#2DD4BF]/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none" />
      </div>
    </div>
  )
}
