// AgentGraph Design System — SwiftUI Theme
// Generated by design-token-bridge-mcp
// Do not edit manually — regenerate from design tokens

import SwiftUI

// MARK: - Colors

extension Color {
    static let agPrimary = Color(red: 0.388, green: 0.400, blue: 0.945)
    static let agPrimaryDark = Color(red: 0.310, green: 0.275, blue: 0.898)
    static let agPrimaryLight = Color(red: 0.506, green: 0.549, blue: 0.973)
    static let agSurface = Color(red: 0.118, green: 0.118, blue: 0.180)
    static let agSurfaceHover = Color(red: 0.165, green: 0.165, blue: 0.243)
    static let agSurfaceElevated = Color(red: 0.145, green: 0.145, blue: 0.220)
    static let agBackground = Color(red: 0.067, green: 0.067, blue: 0.106)
    static let agText = Color(red: 0.804, green: 0.839, blue: 0.957)
    static let agMuted = Color(red: 0.424, green: 0.439, blue: 0.525)
    static let agBorder = Color(red: 0.192, green: 0.196, blue: 0.267)
    static let agSuccess = Color(red: 0.651, green: 0.890, blue: 0.631)
    static let agWarning = Color(red: 0.976, green: 0.886, blue: 0.686)
    static let agDanger = Color(red: 0.953, green: 0.545, blue: 0.659)
    static let agAccent = Color(red: 0.537, green: 0.706, blue: 0.980)
}

// MARK: - Typography

struct AGTypography {
    static let xs = Font.custom("Inter", size: 12)
    static let sm = Font.custom("Inter", size: 14)
    static let base = Font.custom("Inter", size: 16)
    static let lg = Font.custom("Inter", size: 18)
    static let xl = Font.custom("Inter", size: 20)
    static let xxl = Font.custom("Inter", size: 24)
    static let xxxl = Font.custom("Inter", size: 30)
    static let display = Font.custom("Inter", size: 36)
    static let hero = Font.custom("Inter", size: 48)
}

// MARK: - Spacing

struct AGSpacing {
    static let xs: CGFloat = 4
    static let sm: CGFloat = 8
    static let md: CGFloat = 12
    static let base: CGFloat = 16
    static let lg: CGFloat = 20
    static let xl: CGFloat = 24
    static let xxl: CGFloat = 32
    static let xxxl: CGFloat = 48
    static let huge: CGFloat = 64
}

// MARK: - Corner Radii

struct AGRadii {
    static let sm: CGFloat = 4
    static let md: CGFloat = 6
    static let lg: CGFloat = 8
    static let xl: CGFloat = 12
    static let xxl: CGFloat = 16
    static let full: CGFloat = 9999
}

// MARK: - Shadows

extension View {
    func agShadowSm() -> some View {
        self.shadow(color: .black.opacity(0.3), radius: 2, x: 0, y: 1)
    }
    func agShadowMd() -> some View {
        self.shadow(color: .black.opacity(0.3), radius: 6, x: 0, y: 4)
    }
    func agShadowLg() -> some View {
        self.shadow(color: .black.opacity(0.3), radius: 30, x: 0, y: 8)
    }
    func agGlowPrimary() -> some View {
        self.shadow(color: .agPrimary.opacity(0.5), radius: 20, x: 0, y: 0)
    }
}

// MARK: - Liquid Glass (iOS 26+)

@available(iOS 26.0, *)
extension View {
    func agGlassEffect() -> some View {
        self.glassEffect(.regular.tint(.agPrimary))
    }
    func agGlassSubtle() -> some View {
        self.glassEffect(.regular)
    }
}

@available(iOS 26.0, *)
struct AGGlassCard<Content: View>: View {
    let content: Content

    init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }

    var body: some View {
        content
            .padding(AGSpacing.xl)
            .clipShape(RoundedRectangle(cornerRadius: AGRadii.xl))
            .glassEffect(.regular)
    }
}
