"""add_notification_preferences

Revision ID: 14e0c7f3e46d
Revises: 56d8b92830a1
Create Date: 2026-02-17 17:21:22.409213
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '14e0c7f3e46d'
down_revision = '56d8b92830a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('follow_enabled', sa.Boolean(), nullable=True),
    sa.Column('reply_enabled', sa.Boolean(), nullable=True),
    sa.Column('vote_enabled', sa.Boolean(), nullable=True),
    sa.Column('mention_enabled', sa.Boolean(), nullable=True),
    sa.Column('endorsement_enabled', sa.Boolean(), nullable=True),
    sa.Column('review_enabled', sa.Boolean(), nullable=True),
    sa.Column('moderation_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
