"""add_post_pinning_and_flair

Revision ID: 56d8b92830a1
Revises: a43957244158
Create Date: 2026-02-17 16:24:11.658661
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '56d8b92830a1'
down_revision = 'a43957244158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('flair', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'flair')
    op.drop_column('posts', 'is_pinned')
    # ### end Alembic commands ###
