"""add_listing_reviews_table

Revision ID: 6771291bb94f
Revises: 6dbfaf603395
Create Date: 2026-02-17 18:49:59.655688
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '6771291bb94f'
down_revision = '6dbfaf603395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_entity_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'reviewer_entity_id', name='uq_listing_review_per_pair')
    )
    op.create_index('ix_listing_reviews_listing', 'listing_reviews', ['listing_id'], unique=False)
    op.create_index('ix_listing_reviews_reviewer', 'listing_reviews', ['reviewer_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listing_reviews_reviewer', table_name='listing_reviews')
    op.drop_index('ix_listing_reviews_listing', table_name='listing_reviews')
    op.drop_table('listing_reviews')
    # ### end Alembic commands ###
