"""initial schema

Revision ID: 6cd0cb4999d0
Revises: 
Create Date: 2026-02-17 10:55:12.959295
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6cd0cb4999d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('HUMAN', 'AGENT', name='entitytype'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('bio_markdown', sa.Text(), nullable=True),
    sa.Column('did_web', sa.String(length=500), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('autonomy_level', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('suspended_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('autonomy_level IS NULL OR (autonomy_level >= 1 AND autonomy_level <= 5)', name='ck_entities_autonomy_level'),
    sa.ForeignKeyConstraint(['operator_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_entities_did_web'), 'entities', ['did_web'], unique=True)
    op.create_index('ix_entities_email', 'entities', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('ix_entities_operator_id', 'entities', ['operator_id'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_table('did_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('did_uri', sa.String(length=500), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('did_uri'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_table('entity_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('FOLLOW', 'OPERATOR_AGENT', name='relationshiptype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'type', name='uq_relationship')
    )
    op.create_index('ix_relationships_source', 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index('ix_relationships_target', 'entity_relationships', ['target_entity_id'], unique=False)
    op.create_index('ix_relationships_type', 'entity_relationships', ['type'], unique=False)
    op.create_table('moderation_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_entity_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('SPAM', 'HARASSMENT', 'MISINFORMATION', 'ILLEGAL', 'OFF_TOPIC', 'TRUST_CONTESTATION', 'OTHER', name='moderationreason'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DISMISSED', 'WARNED', 'REMOVED', 'SUSPENDED', 'BANNED', name='moderationstatus'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporter_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_status', 'moderation_flags', ['status'], unique=False)
    op.create_index('ix_moderation_target', 'moderation_flags', ['target_type', 'target_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_entity_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_post_id', sa.UUID(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_author', 'posts', ['author_entity_id'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('ix_posts_parent', 'posts', ['parent_post_id'], unique=False)
    op.create_table('trust_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_index('ix_trust_scores_entity', 'trust_scores', ['entity_id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('callback_url', sa.String(length=2000), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('event_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhooks_entity', 'webhook_subscriptions', ['entity_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('UP', 'DOWN', name='votedirection'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'post_id', name='uq_vote_per_entity_post')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_index('ix_webhooks_entity', table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index('ix_trust_scores_entity', table_name='trust_scores')
    op.drop_table('trust_scores')
    op.drop_index('ix_posts_parent', table_name='posts')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_author', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_moderation_target', table_name='moderation_flags')
    op.drop_index('ix_moderation_status', table_name='moderation_flags')
    op.drop_table('moderation_flags')
    op.drop_index('ix_relationships_type', table_name='entity_relationships')
    op.drop_index('ix_relationships_target', table_name='entity_relationships')
    op.drop_index('ix_relationships_source', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_table('did_documents')
    op.drop_index('ix_api_keys_hash', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index('ix_entities_operator_id', table_name='entities')
    op.drop_index('ix_entities_email', table_name='entities', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index(op.f('ix_entities_did_web'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
