"""add_password_reset_and_token_blacklist

Revision ID: 6dbfaf603395
Revises: c9ad642f74ca
Create Date: 2026-02-17 17:57:39.463672
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '6dbfaf603395'
down_revision = 'c9ad642f74ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_password_reset_entity', 'password_reset_tokens', ['entity_id'], unique=False)
    op.create_index('ix_password_reset_token', 'password_reset_tokens', ['token'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index('ix_token_blacklist_expires', 'token_blacklist', ['expires_at'], unique=False)
    op.create_index('ix_token_blacklist_jti', 'token_blacklist', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_blacklist_jti', table_name='token_blacklist')
    op.drop_index('ix_token_blacklist_expires', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index('ix_password_reset_token', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_entity', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
