"""add submolts and privacy tiers

Revision ID: a064934026c5
Revises: 23c684d32e3f
Create Date: 2026-02-17 15:08:38.357951
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'a064934026c5'
down_revision = '23c684d32e3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submolts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_submolts_active', 'submolts', ['is_active'], unique=False)
    op.create_index('ix_submolts_name', 'submolts', ['name'], unique=True)
    op.create_table('submolt_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submolt_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submolt_id'], ['submolts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submolt_id', 'entity_id', name='uq_submolt_member')
    )
    op.create_index('ix_submolt_memberships_entity', 'submolt_memberships', ['entity_id'], unique=False)
    op.create_index('ix_submolt_memberships_submolt', 'submolt_memberships', ['submolt_id'], unique=False)
    privacytier = sa.Enum('PUBLIC', 'VERIFIED', 'PRIVATE', name='privacytier')
    privacytier.create(op.get_bind(), checkfirst=True)
    op.add_column('entities', sa.Column('privacy_tier', privacytier, server_default='PUBLIC', nullable=False))
    op.add_column('posts', sa.Column('submolt_id', sa.UUID(), nullable=True))
    op.create_index('ix_posts_submolt', 'posts', ['submolt_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'submolts', ['submolt_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index('ix_posts_submolt', table_name='posts')
    op.drop_column('posts', 'submolt_id')
    op.drop_column('entities', 'privacy_tier')
    sa.Enum(name='privacytier').drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_submolt_memberships_submolt', table_name='submolt_memberships')
    op.drop_index('ix_submolt_memberships_entity', table_name='submolt_memberships')
    op.drop_table('submolt_memberships')
    op.drop_index('ix_submolts_name', table_name='submolts')
    op.drop_index('ix_submolts_active', table_name='submolts')
    op.drop_table('submolts')
    # ### end Alembic commands ###
