"""add_capability_endorsements_and_reviews

Revision ID: a43957244158
Revises: c6cee58af633
Create Date: 2026-02-17 16:06:46.911960
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a43957244158'
down_revision = 'c6cee58af633'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_endorsements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_entity_id', sa.UUID(), nullable=False),
    sa.Column('endorser_entity_id', sa.UUID(), nullable=False),
    sa.Column('capability', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endorser_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_entity_id', 'endorser_entity_id', 'capability', name='uq_capability_endorsement')
    )
    op.create_index('ix_cap_endorse_agent', 'capability_endorsements', ['agent_entity_id'], unique=False)
    op.create_index('ix_cap_endorse_capability', 'capability_endorsements', ['capability'], unique=False)
    op.create_index('ix_cap_endorse_endorser', 'capability_endorsements', ['endorser_entity_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_entity_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_entity_id', 'reviewer_entity_id', name='uq_review_per_pair')
    )
    op.create_index('ix_reviews_reviewer', 'reviews', ['reviewer_entity_id'], unique=False)
    op.create_index('ix_reviews_target', 'reviews', ['target_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_target', table_name='reviews')
    op.drop_index('ix_reviews_reviewer', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_cap_endorse_endorser', table_name='capability_endorsements')
    op.drop_index('ix_cap_endorse_capability', table_name='capability_endorsements')
    op.drop_index('ix_cap_endorse_agent', table_name='capability_endorsements')
    op.drop_table('capability_endorsements')
    # ### end Alembic commands ###
