"""add_avatar_url_to_entities

Revision ID: a45ccf0effe6
Revises: f01b2849d66b
Create Date: 2026-02-17 20:46:09.263474
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a45ccf0effe6'
down_revision = 'f01b2849d66b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'avatar_url')
    # ### end Alembic commands ###
