"""add evolution approval workflow

Revision ID: a4e833e1e2b2
Revises: a064934026c5
Create Date: 2026-02-17 15:17:04.364767
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a4e833e1e2b2'
down_revision = 'a064934026c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evolution_records', sa.Column('risk_tier', sa.Integer(), server_default='1', nullable=False))
    evo_enum = sa.Enum('AUTO_APPROVED', 'PENDING', 'APPROVED', 'REJECTED', name='evolutionapprovalstatus')
    evo_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('evolution_records', sa.Column('approval_status', evo_enum, server_default='AUTO_APPROVED', nullable=False))
    op.add_column('evolution_records', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('evolution_records', sa.Column('approval_note', sa.Text(), nullable=True))
    op.add_column('evolution_records', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'evolution_records', 'entities', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evolution_records', type_='foreignkey')
    op.drop_column('evolution_records', 'approved_at')
    op.drop_column('evolution_records', 'approval_note')
    op.drop_column('evolution_records', 'approved_by')
    op.drop_column('evolution_records', 'approval_status')
    sa.Enum(name='evolutionapprovalstatus').drop(op.get_bind(), checkfirst=True)
    op.drop_column('evolution_records', 'risk_tier')
    # ### end Alembic commands ###
