"""add entity blocks table

Revision ID: a83607b4ac88
Revises: a4e833e1e2b2
Create Date: 2026-02-17 15:25:47.845805
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a83607b4ac88'
down_revision = 'a4e833e1e2b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_entity_block')
    )
    op.create_index('ix_entity_blocks_blocked', 'entity_blocks', ['blocked_id'], unique=False)
    op.create_index('ix_entity_blocks_blocker', 'entity_blocks', ['blocker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_blocks_blocker', table_name='entity_blocks')
    op.drop_index('ix_entity_blocks_blocked', table_name='entity_blocks')
    op.drop_table('entity_blocks')
    # ### end Alembic commands ###
