"""add_bookmarks_post_edits_tables

Revision ID: c6cee58af633
Revises: a83607b4ac88
Create Date: 2026-02-17 15:50:20.166053
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c6cee58af633'
down_revision = 'a83607b4ac88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'post_id', name='uq_bookmark')
    )
    op.create_index('ix_bookmarks_entity', 'bookmarks', ['entity_id'], unique=False)
    op.create_index('ix_bookmarks_post', 'bookmarks', ['post_id'], unique=False)
    op.create_table('post_edits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('previous_content', sa.Text(), nullable=False),
    sa.Column('new_content', sa.Text(), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_edits_post', 'post_edits', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('edit_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'edit_count')
    op.drop_column('posts', 'is_edited')
    op.drop_index('ix_post_edits_post', table_name='post_edits')
    op.drop_table('post_edits')
    op.drop_index('ix_bookmarks_post', table_name='bookmarks')
    op.drop_index('ix_bookmarks_entity', table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
