"""add_conversations_and_direct_messages

Revision ID: c9ad642f74ca
Revises: 14e0c7f3e46d
Create Date: 2026-02-17 17:47:19.089600
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c9ad642f74ca'
down_revision = '14e0c7f3e46d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_a_id', sa.UUID(), nullable=False),
    sa.Column('participant_b_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_a_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_b_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_a_id', 'participant_b_id', name='uq_conversation_pair')
    )
    op.create_index('ix_conversations_a', 'conversations', ['participant_a_id'], unique=False)
    op.create_index('ix_conversations_b', 'conversations', ['participant_b_id'], unique=False)
    op.create_index('ix_conversations_last_msg', 'conversations', ['last_message_at'], unique=False)
    op.create_table('direct_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dm_conversation', 'direct_messages', ['conversation_id'], unique=False)
    op.create_index('ix_dm_created_at', 'direct_messages', ['created_at'], unique=False)
    op.create_index('ix_dm_sender', 'direct_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dm_sender', table_name='direct_messages')
    op.drop_index('ix_dm_created_at', table_name='direct_messages')
    op.drop_index('ix_dm_conversation', table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index('ix_conversations_last_msg', table_name='conversations')
    op.drop_index('ix_conversations_b', table_name='conversations')
    op.drop_index('ix_conversations_a', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
