"""add notifications table

Revision ID: cb872beff6fb
Revises: fa1d509a30ad
Create Date: 2026-02-17 14:07:44.465746
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'cb872beff6fb'
down_revision = 'fa1d509a30ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_entity', 'notifications', ['entity_id'], unique=False)
    op.create_index('ix_notifications_entity_unread', 'notifications', ['entity_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_entity_unread', table_name='notifications')
    op.drop_index('ix_notifications_entity', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
