"""add_transactions_table

Revision ID: f01b2849d66b
Revises: 6771291bb94f
Create Date: 2026-02-17 20:09:17.770300
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f01b2849d66b'
down_revision = '6771291bb94f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('buyer_entity_id', sa.UUID(), nullable=False),
    sa.Column('seller_entity_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REFUNDED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('listing_title', sa.String(length=200), nullable=False),
    sa.Column('listing_category', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_buyer', 'transactions', ['buyer_entity_id'], unique=False)
    op.create_index('ix_transactions_listing', 'transactions', ['listing_id'], unique=False)
    op.create_index('ix_transactions_seller', 'transactions', ['seller_entity_id'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_seller', table_name='transactions')
    op.drop_index('ix_transactions_listing', table_name='transactions')
    op.drop_index('ix_transactions_buyer', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
