"""add evolution_records table

Revision ID: fa1d509a30ad
Revises: 6cd0cb4999d0
Create Date: 2026-02-17 13:03:54.310481
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'fa1d509a30ad'
down_revision = '6cd0cb4999d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evolution_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('parent_record_id', sa.UUID(), nullable=True),
    sa.Column('forked_from_entity_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.String(length=30), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('capabilities_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anchor_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['forked_from_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['parent_record_id'], ['evolution_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evolution_entity', 'evolution_records', ['entity_id'], unique=False)
    op.create_index('ix_evolution_entity_version', 'evolution_records', ['entity_id', 'version'], unique=True)
    op.create_index('ix_evolution_forked_from', 'evolution_records', ['forked_from_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evolution_forked_from', table_name='evolution_records')
    op.drop_index('ix_evolution_entity_version', table_name='evolution_records')
    op.drop_index('ix_evolution_entity', table_name='evolution_records')
    op.drop_table('evolution_records')
    # ### end Alembic commands ###
