"""Deactivate synthetic Moltbook profiles and create recruitment_prospects table.

Moltbook profiles were synthetic (generated by scripts), not real imports.
This migration deactivates them and adds infrastructure for real operator
recruitment via GitHub outreach.

Revision ID: s16_recruit
Revises: s15_lb_perf
Create Date: 2026-03-22
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

revision = "s16_recruit"
down_revision = "s15_lb_perf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Deactivate synthetic Moltbook profiles
    op.execute(
        "UPDATE entities SET is_active = false WHERE source_type = 'moltbook'"
    )

    # Create recruitment_prospects table
    op.create_table(
        "recruitment_prospects",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("platform", sa.String(50), nullable=False),
        sa.Column("platform_id", sa.String(500), nullable=False),
        sa.Column("owner_login", sa.String(200), nullable=False),
        sa.Column("repo_name", sa.String(500)),
        sa.Column("stars", sa.Integer, server_default="0"),
        sa.Column("description", sa.Text),
        sa.Column("framework_detected", sa.String(100)),
        sa.Column("status", sa.String(50), server_default="'discovered'"),
        sa.Column("contacted_at", sa.DateTime(timezone=True)),
        sa.Column("issue_url", sa.String(500)),
        sa.Column("notes", sa.Text),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True),
            server_default=sa.text("now()"), nullable=False,
        ),
        sa.UniqueConstraint("platform", "platform_id", name="uq_recruitment_platform_id"),
    )
    op.create_index("ix_recruitment_status", "recruitment_prospects", ["status"])
    op.create_index("ix_recruitment_owner", "recruitment_prospects", ["owner_login"])


def downgrade() -> None:
    op.drop_index("ix_recruitment_owner")
    op.drop_index("ix_recruitment_status")
    op.drop_table("recruitment_prospects")

    # Re-activate Moltbook profiles (best-effort reverse)
    op.execute(
        "UPDATE entities SET is_active = true WHERE source_type = 'moltbook'"
    )
