// AgentGraph Design System — Material 3 Theme
// Generated by design-token-bridge-mcp
// Do not edit manually — regenerate from design tokens

package com.agentgraph.ui.theme

import androidx.compose.material3.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.unit.dp
import androidx.compose.runtime.Composable

// --- Colors ---

object AGColors {
    val Primary = Color(0xFF6366F1)
    val PrimaryDark = Color(0xFF4F46E5)
    val PrimaryLight = Color(0xFF818CF8)
    val Surface = Color(0xFF1E1E2E)
    val SurfaceHover = Color(0xFF2A2A3E)
    val SurfaceElevated = Color(0xFF252538)
    val Background = Color(0xFF11111B)
    val Text = Color(0xFFCDD6F4)
    val Muted = Color(0xFF6C7086)
    val Border = Color(0xFF313244)
    val Success = Color(0xFFA6E3A1)
    val Warning = Color(0xFFF9E2AF)
    val Danger = Color(0xFFF38BA8)
    val Accent = Color(0xFF89B4FA)
    val PrimaryGlow = Color(0x806366F1)
    val AccentGlow = Color(0x6089B4FA)
    val SuccessGlow = Color(0x40A6E3A1)
}

// --- Light Colors ---

object AGColorsLight {
    val Surface = Color(0xFFFFFFFF)
    val SurfaceHover = Color(0xFFF1F5F9)
    val Background = Color(0xFFF8FAFC)
    val Text = Color(0xFF1E293B)
    val Muted = Color(0xFF64748B)
    val Border = Color(0xFFE2E8F0)
    val Success = Color(0xFF16A34A)
    val Warning = Color(0xFFCA8A04)
    val Danger = Color(0xFFDC2626)
    val Accent = Color(0xFF2563EB)
}

// --- Color Schemes ---

val AGDarkColorScheme = darkColorScheme(
    primary = AGColors.Primary,
    onPrimary = Color.White,
    primaryContainer = AGColors.PrimaryDark,
    secondary = AGColors.Accent,
    surface = AGColors.Surface,
    onSurface = AGColors.Text,
    background = AGColors.Background,
    onBackground = AGColors.Text,
    error = AGColors.Danger,
    outline = AGColors.Border,
)

val AGLightColorScheme = lightColorScheme(
    primary = AGColors.Primary,
    onPrimary = Color.White,
    primaryContainer = AGColors.PrimaryLight,
    secondary = AGColorsLight.Accent,
    surface = AGColorsLight.Surface,
    onSurface = AGColorsLight.Text,
    background = AGColorsLight.Background,
    onBackground = AGColorsLight.Text,
    error = AGColorsLight.Danger,
    outline = AGColorsLight.Border,
)

// --- Typography ---

val AGTypography = Typography(
    displayLarge = TextStyle(fontSize = 72.sp, fontWeight = FontWeight.ExtraBold),
    displayMedium = TextStyle(fontSize = 60.sp, fontWeight = FontWeight.Bold),
    displaySmall = TextStyle(fontSize = 48.sp, fontWeight = FontWeight.Bold),
    headlineLarge = TextStyle(fontSize = 36.sp, fontWeight = FontWeight.Bold),
    headlineMedium = TextStyle(fontSize = 30.sp, fontWeight = FontWeight.SemiBold),
    headlineSmall = TextStyle(fontSize = 24.sp, fontWeight = FontWeight.SemiBold),
    titleLarge = TextStyle(fontSize = 20.sp, fontWeight = FontWeight.Medium),
    titleMedium = TextStyle(fontSize = 18.sp, fontWeight = FontWeight.Medium),
    titleSmall = TextStyle(fontSize = 16.sp, fontWeight = FontWeight.Medium),
    bodyLarge = TextStyle(fontSize = 16.sp, fontWeight = FontWeight.Normal),
    bodyMedium = TextStyle(fontSize = 14.sp, fontWeight = FontWeight.Normal),
    bodySmall = TextStyle(fontSize = 12.sp, fontWeight = FontWeight.Normal),
    labelLarge = TextStyle(fontSize = 14.sp, fontWeight = FontWeight.Medium),
    labelMedium = TextStyle(fontSize = 12.sp, fontWeight = FontWeight.Medium),
    labelSmall = TextStyle(fontSize: 10.sp, fontWeight = FontWeight.Medium),
)

// --- Shapes ---

val AGShapes = Shapes(
    extraSmall = RoundedCornerShape(4.dp),
    small = RoundedCornerShape(6.dp),
    medium = RoundedCornerShape(8.dp),
    large = RoundedCornerShape(12.dp),
    extraLarge = RoundedCornerShape(16.dp),
)

// --- Theme ---

@Composable
fun AgentGraphTheme(
    darkTheme: Boolean = true,
    content: @Composable () -> Unit
) {
    val colorScheme = if (darkTheme) AGDarkColorScheme else AGLightColorScheme

    MaterialTheme(
        colorScheme = colorScheme,
        typography = AGTypography,
        shapes = AGShapes,
        content = content,
    )
}
